### ISSUE TITLE
No support for emojis in the comments 😿

### ISSUE THREAD

**Issue by marsrobertson** [rkalis/truffle-plugin-verify#56]
> General exception occured when attempting to insert record
> Failed to verify 1 contract(s): Assurance

Running with `--debug`

Noticed emoji in the comments.

Removed emoji.

Now works.

**Comment by rkalis** [comment]
That sounds interesting! I'll look into this some time on the weekend.

**Comment by rkalis** [comment]
Actually let me tag @Enigmatic331 as well since the the error message appears to come form the Etherscan side.

**Comment by felixakiragreen** [comment]
I'm running into the same issue where I am am trying to verify a contract that has already been deployed to mainnet. 

If it includes the emojis/special characters in the comments it fails, but without them it succeeds. (On testnet)

Unfortunately my contract is already deployed on mainnet.

@rkalis @marsrobertson Are you aware of any way to do the verification if it already includes the emojis/special characters? I now know not to include them for the future, but I'm a little stuck right now since I already deployed it weeks ago.

**Comment by rkalis** [comment]
You should be able to change the comments and still get it to verify on Etherscan since the comments don't impact the bytecode. In other words the comments in the verified version don't have to be exactly the same as in the deployed version.

**Comment by felixakiragreen** [comment]
@rkalis 🙏 thanks so much. Trying now!

**Comment by rkalis** [comment]
@Enigmatic331 do you have any idea why emojis cannot occur in the comments when submitting for verification?

**Comment by lebed2045** [comment]
lol, I can confirm this behaviour for https://testnet.bscscan.com/address/0xa8Ebf9a20aD4F9226346729BB0d4AEf67Eda185E#contracts - wasn't able to verify untill I removed 🐧

**Comment by rkalis** [comment]
@Enigmatic332 can I bump this to your attention, any idea why emojis are not allowed?

**Comment by Enigmatic331** [comment]
Ah crap - I think I fixed this but forget to mention this - One sec...

**Comment by rkalis** [comment]
Thanks @Enigmatic331! I'll close this issue now.
